export const academics = [
  { imgSource: "https://i.ibb.co/dcHKR96/Anamitra-Sengupta.webp",
    name: "Anamitra Sengupta", position: "Under Secretary General"},
  { imgSource: "https://i.ibb.co/Jvszb6M/Priti-Das-Acads.webp",
      name: "Priti Das", position: "Under Secretary General"},
  { imgSource: "https://i.ibb.co/wrCdD41/shreya-verma-Academics.webp",
      name: "Shreya Verma", position: "Director"},
  { imgSource: "https://i.ibb.co/HGP9tV6/Pratyush-Saran-Academics.webp",
      name: "Pratyush Saran", position: "Director"},
  { imgSource: "https://i.ibb.co/25zYNQ6/Chhavi-Soin.webp",
      name: "Chhavi Soin", position: "Deputy Director" },
  { imgSource: "https://i.ibb.co/X3nq6KZ/Bibhukalyani-Swain-Academics.webp",
    name: "Bibhukalyani Swain", position: "Officer" },
  { imgSource: "https://i.ibb.co/nB6xLzM/Drohita-Dhar-Academics.webp",
    name: "Drohita Dhar", position: "Officer" },
  { imgSource: "https://i.ibb.co/BZ8YQBv/Ketan-Chauhan.webp",
    name: "Ketan Chauhan", position: "Officer" },
  { imgSource: "https://i.ibb.co/PM6rXSj/Omm-Gupta-Academiics.webp",
    name: "Omm Gupta", position: "Officer" },
  { imgSource: "https://i.ibb.co/jLTbB6d/Pallavi-Kumari-Academics.webp",
    name: "Pallavi Kumari", position: "Officer" },
  { imgSource: "https://i.ibb.co/F5d2M6z/Riya-Singh.webp",
    name: "Riya Singh", position: "Officer" },
  { imgSource: "https://i.ibb.co/ggpt8v8/Sarvagya-Singh-Academics.webp",
    name: "Sarvagya Singh", position: "Officer" },
  { imgSource: "https://i.ibb.co/wMzpL6N/Sudipta-Subham-Sahu.webp",
    name: "Sudipta Subham Sahu", position: "Officer" },
  { imgSource: "https://i.ibb.co/pZg182b/Utkrisht-Bhandari-Academics.webp",
    name: "Utkrisht Bhandari", position: "Officer" },
  { imgSource: "https://i.ibb.co/b6nyGh8/Yashvi-Academics.webp",
    name: "Yashvi", position: "Officer" },
];
