export const broadcasting = [
    { imgSource: "https://i.ibb.co/jGBz4MT/Shubham-Mahapatra-broadcasting-LEAD.webp",
        name: "Shubham Mahapatra", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/QJrdG4Y/Ashmit-debroy-Broadcasting.webp",
        name: "Ashmit Deb Roy", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/vwHXsKX/Swapnil-Patro-broadcasting.webp",
        name: "Swapnil Patro", position: "Director" },
    { imgSource: "https://i.ibb.co/Q9PXgsq/Pratik-Mohanty-Broadcasting.webp",
        name: "Pratik Mohanty", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/gZHWFTR/Abhinav-Anand-Broadcasting.webp",
      name: "Abhinav Anand", position: "Officer" },
    { imgSource: "https://i.ibb.co/30ptNBg/Advik-Broadcasting.webp",
      name: "Advik", position: "Officer" },
    { imgSource: "https://i.ibb.co/Y8ZSHJf/Adwaith-PJ-Broadcasting.webp",
      name: "Adwaith PJ", position: "Officer" },
    { imgSource: "https://i.ibb.co/nQr41MP/Ayush-Dutta-Broadcasting.webp",
      name: "Ayush Dutta", position: "Officer" },
    { imgSource: "https://i.ibb.co/HT2HXYx/DSC-2616.webp",
        name: "Chirag Kar", position: "Officer" },
    { imgSource: "https://i.ibb.co/JqFZPkm/Hritom-Broadcasting.webp",
      name: "Hritom Mallick", position: "Officer" },
    { imgSource: "https://i.ibb.co/x8dPMBh/Pranjali-Yadav-Broadcasting.webp",
      name: "Pranjali Yadav", position: "Officer" },
    { imgSource: "https://i.ibb.co/cTRZCL4/Priyam-Ghoshal.webp",
      name: "Priyam Ghoshal", position: "Officer" },
    { imgSource: "https://i.ibb.co/jZC2Ldc/Rishi-Raj-Broadcasting.webp",
      name: "Rishi Raj Dutta", position: "Officer" },
    { imgSource: "https://i.ibb.co/K6T2cpB/Ritusome-Das-Broadcasting.webp",
      name: "Ritusome Das", position: "Officer" },
    { imgSource: "https://i.ibb.co/k5Zv1RC/Sai-Sarangi-Broadcasting.webp",
      name: "Sai Sarangi", position: "Officer" },
    { imgSource: "https://i.ibb.co/nnKf3N8/Sampreet-veer-singh-Broadcasting.webp",
      name: "Sampreet Veer Singh", position: "Officer" },
    { imgSource: "https://i.ibb.co/2vbjtgQ/Sanidhya-Mohan-Broadcasting.webp",
      name: "Sanidhya Mohan", position: "Officer" },
    { imgSource: "https://i.ibb.co/R3btH0P/Sashreek-Broadcasting.webp",
      name: "Sashreek Das", position: "Officer" },
    { imgSource: "https://i.ibb.co/rygh94M/Shaswat-Sinha-Broadcasting.webp",
      name: "Shashwat Sinha", position: "Officer" },
    { imgSource: "https://i.ibb.co/4RL9341/Srikar-Broadcasting.webp",
        name: "Srikar", position: "Officer" },
    { imgSource: "https://i.ibb.co/1r4DpjZ/Vishal-Broadcasting-1.webp",
        name: "Vishal Kumar Sahoo", position: "Officer" },
]