export const DigiMakreting =[
    { imgSource: "https://i.ibb.co/bJB0dC8/Chiranjeeb-Rout-Digi-Marketing.webp",
        name: "Chiranjeeb Rout", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/jVWm0GD/Shreya-jha.webp",
        name: "Shreya Jha", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/WG0jnH3/Adrija-Mitra-Digital-Marketing.webp",
        name: "Adrija Mitra", position: "Director" },
    { imgSource: "https://i.ibb.co/PzrSyXG/Ayush-Amulya.webp",
        name: "Ayush Amulya", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/604K3JL/SHIVAM-KUMAR-SINGH.webp",
        name: "Shivam Kumar Singh", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/VDHYLCm/Anjani.webp",
        name: "Anjani Kumar Nayak", position: "Officer" },
    { imgSource: "https://i.ibb.co/C1DRFh9/Prachi-Prakash.webp",
        name: "Prachi Prakash", position: "Officer" },
    { imgSource: "https://i.ibb.co/tmHwrsw/Ramgopal-Digi-Marketing.webp",
        name: "Ramgopal Raula", position: "Officer" },
    { imgSource: "https://i.ibb.co/wssWqGF/Shivam-Singh.webp",
        name: "Shivam Singh", position: "Officer" },
    { imgSource: "https://i.ibb.co/kxzZKGX/SOUMYA-RANJAN-SAHOO.webp",
        name: "Soumya Ranjan Sahoo", position: "Officer" },
    { imgSource: "https://i.ibb.co/dbbY3GY/Sushil-Kumar.webp",
        name: "Sushil Kumar", position: "Officer" },
]