export const Hospitality = [
    { imgSource: "https://i.ibb.co/8NyX6vG/Harsh-Raj-Hospitality.webp",
        name: "Harsh Raj", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/MVmLkDX/Nishant-naman-Hospitality.webp",
        name: "Nishant Naman", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/ByNfTQT/Brajesh-Mishra-Hospitality.webp",
        name: "Brajesh Mishra", position: "Director" },
    { imgSource: "https://i.ibb.co/thfzYk8/Izhaar-Arief-Hospitality.webp",
        name: "Izhaar Arief", position: "Director" },
    { imgSource: "https://i.ibb.co/L0Y7M34/Prabir-Kumar-Nayak-Hospitality.webp",
        name: "Prabir Kumar Nayak", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/VCbfGsq/Adarsh-Kumar-Pandey-Hospitality.webp",
        name: "Adarsh Kumar Pandey", position: "Officer" },
    { imgSource: "https://i.ibb.co/r2Yp9t6/Aditya-Raj-Hospitality.webp",
        name: "Aditya Raj", position: "Officer" },
    { imgSource: "https://i.ibb.co/YjVq2kK/Akash-Ojha-Hospitality.webp",
        name: "Akash Ojha", position: "Officer" },
        { imgSource: "https://i.ibb.co/vh8cqQg/Armaan.webp",
        name: "Armaan Saraswat", position: "Officer" },
    { imgSource: "https://i.ibb.co/QCTvZ4y/Ashutosh-Rout-Hospitality.webp",
        name: "Ashutosh Rout", position: "Officer" },
    { imgSource: "https://i.ibb.co/0rSfVbD/Neeshikant-Nanda-Hospitality.webp",
        name: "Neeshikant Nanda", position: "Officer" },
    { imgSource: "https://i.ibb.co/5r4NJgd/Salonee-Mishra-Hospitality.webp",
        name: "Salonee Mishra", position: "Officer" },
    { imgSource: "https://i.ibb.co/XLtZ9rY/Shubham-Kumar-Hospitality.webp",
        name: "Shubham Kumar", position: "Officer" },
    { imgSource: "https://i.ibb.co/9whtYvn/Srutishree-Priyadarsani-Rout-Hospitality.webp",
        name: "Srutishree Priyadarsani Rout", position: "Officer" },
    { imgSource: "https://i.ibb.co/SwDxwqV/Subhasmita-Babu-Hospitality.webp",
        name: "Subhasmita Babu", position: "Officer" },
    { imgSource: "https://i.ibb.co/25t3Jq8/Swastika-rai-Hospitality.webp",
        name: "Swastika Rai", position: "Officer" },

]