export const Intoutreach =[
    { imgSource: "https://i.ibb.co/CKKFnqF/Siddhartha-Pradhan-Outreach.webp",
        name: "Siddhartha Pradhan", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/gMhz9X1/Tannistha-Roy-Outreach.webp",
        name: "Tannistha Roy", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/MS856cR/Utkarsh-Outreach.webp",
        name: "Utkarsh", position: "Director" },
    { imgSource: "https://i.ibb.co/dmydmsZ/Raghav-Naulakha-Outreach.webp",
        name: "Raghav Naulakha", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/RHqx9P1/Dipayan-Saha-Outreach-1.webp",
        name: "Dipayan Saha", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/JjXwY4n/Aditya-Thakur-Outreach.webp",
        name: "Aditya Thakur", position: "Officer" },
    { imgSource: "https://i.ibb.co/HD75hfR/Aritra-Pattanayak-Outreach.webp",
        name: "Aritra Pattanayak", position: "Officer" },
    { imgSource: "https://i.ibb.co/PZ5GQ59/Chitranshi-Outreach.webp",
        name: "Chitranshi", position: "Officer" },
    { imgSource: "https://i.ibb.co/L9zNrFK/Divyanshi-Tiwary-Outreach.webp",
        name: "Divyanshi Tiwary", position: "Officer" },
    { imgSource: "https://i.ibb.co/MgDdKW2/Harjinder-singh-saini-Outreach.webp",
        name: "Harjinder Singh Saini", position: "Officer" },

]