export const logistics =[
    { imgSource: "https://i.ibb.co/5rBbFJJ/Debabrata-Singh-logistics-1.webp",
        name: "Debabrata Singh", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/h7JX4zw/ahmed-nadeem.webp",
        name: "Ahmed Nadeem", position: "Director" },
    { imgSource: "https://i.ibb.co/Gcs5bcP/Shresth-Sinha.webp",
        name: "Shresth Sinha", position: "Director" },
    { imgSource: "https://i.ibb.co/3hmJ8xZ/Chimoy-rout.webp",
        name: "Chinmaya Ranjan Rout", position: "Director" },
    { imgSource: "https://i.ibb.co/zNx4Z65/Ashirwaad-Dhir-Logistics.webp",
        name: "Ashirwaad Dhir", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/7X5wR6H/Adarsh-Acharya.webp",
        name: "Adarsh Acharya", position: "Officer" },
    { imgSource: "https://i.ibb.co/wy5jtZQ/Debasis-mishra-Logistics.webp",
        name: "Debasis Mishra", position: "Officer" },
    { imgSource: "https://i.ibb.co/jDzm7kB/Rohit-Kumar-Singh-Logistics.webp",
        name: "Rohit Kumar Singh", position: "Officer" },
    { imgSource: "https://i.ibb.co/mbqB1Dn/Shashank-Kashyap-Logistics.webp",
        name: "Shashank Kashyap", position: "Officer" },
    { imgSource: "https://i.ibb.co/ThsY3rv/Yash-Raj-Logistics.webp",
        name: "Yash Raj", position: "Officer" },

]