export const OfflineMaketing = [
    { imgSource: "https://i.ibb.co/yst8x8B/Nishant-Kumar-Singh.webp",
        name: "Nishant Kumar Singh", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/265PMBV/Yash-Chauhan.webp",
        name: "Yash Chauhan", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/Qm0ZjQB/Mayukh-Mala-Das-Offline-Marketing.webp",
        name: "Mayukh Mala Das", position: "Director" },
    { imgSource: "https://i.ibb.co/F8TrcK0/Arvind-Kumar.webp",
        name: "Arvind Kumar", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/1XvJRyY/Ritesh-Rath.webp",
        name: "Ritesh Rath", position: "Deputy Director" },
    { imgSource: "https://i.ibb.co/vcWp4Xy/Anurag-Samantaray.webp",
        name: "Anurag Samantaray", position: "Officer" },
    { imgSource: "https://i.ibb.co/P6jHKBf/Aryan-Malhotra.webp",
        name: "Aryan Malhotra", position: "Officer" },
    { imgSource: "https://i.ibb.co/TLGMFTk/Avinash.webp",
        name: "Avinash", position: "Officer" },
    { imgSource: "https://i.ibb.co/G24j2Pq/Barun-B-Mishra.webp",
        name: "Barun B Mishra", position: "Officer" },
    { imgSource: "https://i.ibb.co/cNTph65/Debolina-Roy.webp",
        name: "Debolina Roy", position: "Officer" },
    { imgSource: "https://i.ibb.co/2nP6QMy/Ishika-Chakraborty.webp",
        name: "Ishika Chakraborty", position: "Officer" },
    { imgSource: "https://i.ibb.co/12NSTsZ/Manpreet-Veer.webp",
        name: "Manpreet Veer", position: "Officer" },
    { imgSource: "https://i.ibb.co/Yhcd945/Mansha-Patra.webp",
        name: "Mansha Patra", position: "Officer" },
    { imgSource: "https://i.ibb.co/rQDcZT7/Naibedya-Mohanty.webp",
        name: "Naibedya Mohanty", position: "Officer" },
    { imgSource: "https://i.ibb.co/j4cCPh4/P-P-sathpathy.webp",
        name: "P P Sathpathy", position: "Officer" },
    { imgSource: "https://i.ibb.co/jRpBRwJ/Pratik-Kumar-Behra-Offline-Marketing.webp",
        name: "Pratik Kumar Behra", position: "Officer" },
    { imgSource: "https://i.ibb.co/60LC29x/Ramniranjan-Bhutra.webp",
        name: "Ramniranjan Bhutra", position: "Officer" },
    { imgSource: "https://i.ibb.co/zQG9VrX/Rishav-Raj.webp",
        name: "Rishav Raj", position: "Officer" },
    { imgSource: "https://i.ibb.co/SRtnCRN/Sahil-Singh.webp",
        name: "Sahil Singh", position: "Officer" },
    { imgSource: "https://i.ibb.co/0ZXfcNR/Shiv-Shankar.webp",
        name: "Shiv Shankar", position: "Officer" },
    { imgSource: "https://i.ibb.co/M5PrYJ2/Siddharth-Himanshee.webp",
        name: "Siddharth Himanshee", position: "Officer" },
    { imgSource: "https://i.ibb.co/Fn6WW7z/Sondeepon-Roy.webp",
        name: "Sondeepon Roy", position: "Officer" },
    { imgSource: "https://i.ibb.co/8myP8hh/Souvik-Roy.webp",
        name: "Souvik Roy", position: "Officer" },
    { imgSource: "https://i.ibb.co/Kh4kBbC/Vikrant-Singh.webp",
        name: "Vikrant Singh", position: "Officer" },


]