export const Operations =[
    { imgSource: "https://i.ibb.co/bXVRd05/Rishab-Barik-Operation.webp",
        name: "Rishab Barik", position: "Under Secretary General" },
    { imgSource: "https://i.ibb.co/hLP5yVR/Roshan-Barik-Operations.webp",
        name: "Roshan Barik", position: "Under Secretary General" },
        { imgSource: "https://i.ibb.co/1qF0L66/Anish-Raj-Operations.webp",
        name: "Anish Raj", position: "Director" },
    { imgSource: "https://i.ibb.co/jhStSD2/Aditya-Sinha-Operations.webp",
        name: "Aditya Sinha", position: "Officer" },
    { imgSource: "https://i.ibb.co/hYpNSjc/Aman-Kumar-Jena-Operations.webp",
        name: "Aman Kumar Jena", position: "Officer" },
    { imgSource: "https://i.ibb.co/6rVbFy2/Amol-Kshitij-Operations.webp",
        name: "Amol Kshitij", position: "Officer" },
    { imgSource: "https://i.ibb.co/cbL2njJ/Ayush-Kumar-Operations.webp",
        name: "Ayush Kumar", position: "Officer" },
    { imgSource: "https://i.ibb.co/vQW4S4r/Harsh-Kumar-Verma-Operations.webp",
        name: "Harsh Kumar Verma", position: "Officer" },
    { imgSource: "https://i.ibb.co/3hX7nqR/Naimish-Pandey.webp",
        name: "Naimish Pandey", position: "Officer" },
    { imgSource: "https://i.ibb.co/qR6L03y/Pranshu-Sahay-Operations.webp",
        name: "Pranshu Sahay", position: "Officer" },
    { imgSource: "https://i.ibb.co/QrrLC67/Prateek-Preet-Pattanaik-Operations.webp",
        name: "Prateek Preet Pattanaik", position: "Officer" },
    { imgSource: "https://i.ibb.co/gJXRq6G/Priyansh-Sharma-Operations.webp",
        name: "Priyansh Sharma", position: "Officer" },
    { imgSource: "https://i.ibb.co/GH3CX5f/Sayash-Sarthak-Operations.webp",
        name: "Sayash Sarthak", position: "Officer" },

]