import type { FormikValues } from "./components/register/Committee"

export const initialValuesSingleDelegate = {
	firstName: "",
	middleName: "",
	lastName: "",
	email: "",
	gender: "",
	country: "",
	phone1: "",
	phone2: "",
	age: "",
	course: "",
	college: "",
	year: "",
	prevExp: "",
	awards: "",
	committeeOne: "", // committeee one
	committeeOne_countryOne: "",
	committeeOne_countryTwo: "",
	committeeOne_countryThree: "",
	committeeTwo: "", // committee two
	committeeTwo_countryOne: "",
	committeeTwo_countryTwo: "",
	committeeTwo_countryThree: "",
	committeeThree: "", // committee three
	committeeThree_countryOne: "",
	committeeThree_countryTwo: "",
	committeeThree_countryThree: "",
	accommodation: "",
	accommodation_type: "",
}

export const initialValuesDoubleDelegate = {
	s_firstName: "",
	s_middleName: "",
	s_lastName: "",
	d_firstName: "",
	d_middleName: "",
	d_lastName: "",
	s_email: "",
	d_email: "",
	s_gender: "",
	d_gender: "",
	s_country: "",
	d_country: "",
	s_phone1: "",
	s_phone2: "",
	d_phone1: "",
	d_phone2: "",
	s_course: "",
	d_course: "",
	s_college: "",
	d_college: "",
	s_age: "",
	d_age: "",
	s_prevExp: "",
	d_prevExp: "",
	s_awards: "",
	d_awards: "",
	committeeOne: "", // committeee one
	committeeOne_countryOne: "",
	committeeOne_countryTwo: "",
	committeeOne_countryThree: "",
	committeeTwo: "", // committee two
	committeeTwo_countryOne: "",
	committeeTwo_countryTwo: "",
	committeeTwo_countryThree: "",
	committeeThree: "", // committee three
	committeeThree_countryOne: "",
	committeeThree_countryTwo: "",
	committeeThree_countryThree: "",
	accommodation: "",
	accommodation_type: "",
}

export const SINGLEDELEGATECOMMITTEE = ["DISEC", "UNCSW", "SC", "UNESCO", "NATO", "Ad Hoc", "UNCND", "GA6 Legal", "UNOOSA", "IP", "UNHRC", "WHA", "COP-28 UNFCCC", "World bank", "ECOSOC"]

export const DOUBLEDELEGATECOMMITTEE = ["UNHRC", "WHA", "COP-28 UNFCCC", "World bank", "ECOSOC"]

export const unfccc = ["Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Cook Islands",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czechia",
	"Democratic People's Republic of Korea",
	"Democratic Republic of the Congo",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"European Union",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Holy See",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia (Federated States of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Republic of Moldova",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"State of Palestine",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkiye",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom of Great Britain and Northern Ireland",
	"United Republic of Tanzania",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"VietNam",
	"Yemen",
	"Zambia",
	"Zimbabwe"
]

export const disec = ["Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Costa Rica",
	"Côte D'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Democratic People's Republic of Korea",
	"Democratic Republic of the Congo",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia (Republic of The)",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People’s Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia (Federated States of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Republic of Moldova",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Türkiye",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom of Great Britain and Northern Ireland",
	"United Republic of Tanzania",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Yemen",
	"Zambia",
	"Zimbabwe"
]

export const ecosoc = ["Afghanistan",
	"Argentina",
	"Belgium",
	"Belize",
	"Bolivia (Plurinational State of)",
	"Botswana",
	"Brazil",
	"Bulgaria",
	"Cabo Verde",
	"Cameroon",
	"Canada",
	"Chile",
	"China",
	"Colombia",
	"Costa Rica",
	"Côte d’Ivoire",
	"Croatia",
	"Czechia",
	"Denmark",
	"Equatorial Guinea",
	"Eswatini",
	"France",
	"Greece",
	"Guatemala",
	"India",
	"Indonesia",
	"Israel",
	"Italy",
	"Japan",
	"Kazakhstan",
	"Lao People’s Democratic Republic",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Madagascar",
	"Mauritius",
	"Mexico",
	"New Zealand",
	"Nigeria",
	"Oman",
	"Peru",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Sweden",
	"Tunisia",
	"United Kingdom of Great Britain and Northern Ireland",
	"United Republic of Tanzania",
	"United States of America",
	"Zimbabwe"
]

export const ga6 = ["Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Brazil",
	"Botswana",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Costa Rica",
	"Côte D'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czechia",
	"Democratic People's Republic of Korea",
	"Democratic Republic of the Congo",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia (Republic of The)",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran ",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People’s Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia (Federated States of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Republic of Moldova",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Türkiye",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom of Great Britain and Northern Ireland",
	"United Republic of Tanzania",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Yemen",
	"Zambia",
	"Zimbabwe"
]

export const nato = ["Albania",
	"Belgium",
	"Bulgaria",
	"Canada",
	"Croatia",
	"Czechia",
	"Denmark",
	"Estonia",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Hungary",
	"Iceland",
	"Italy",
	"Latvia",
	"Lithuania",
	"Luxembourg",
	"Montenegro",
	"Netherlands",
	"North Macedonia",
	"Norway",
	"Poland",
	"Portugal",
	"Romania",
	"Slovakia",
	"Slovenia",
	"Spain",
	"Türkiye",
	"United Kingdom",
	"United States"
]

export const uncnd = ["Algeria",
	"Angola",
	"Australia",
	"Austria",
	"Bahrain",
	"Bangladesh",
	"Belgium",
	"Bolivia (Plurinational State of)",
	"Brazil",
	"Canada",
	"China",
	"Colombia",
	"Côte d’Ivoire",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"France",
	"Germany",
	"Ghana",
	"Hungary",
	"Iran (Islamic Republic of)",
	"Italy",
	"Jamaica",
	"Japan",
	"Kazakhstan",
	"Kenya",
	"Libya",
	"Lithuania",
	"Mexico",
	"Morocco",
	"Nepal",
	"Netherlands",
	"Nigeria",
	"Pakistan",
	"Peru",
	"Poland",
	"Republic of Korea",
	"Russian Federation",
	"Saudi Arabia",
	"Slovenia",
	"South Africa",
	"Spain",
	"Sweden",
	"Switzerland",
	"Thailand",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Ukraine",
	"United Kingdom of Great Britain",
	"United States of America",
	"Uruguay"
]

export const uncsw = ["Afghanistan ",
	"Algeria",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Bangladesh",
	"Belarus",
	"Brazil",
	"Cabo Verde",
	"China",
	"Colombia",
	"Costa Rica",
	"Cuba",
	"Denmark",
	"Dominican Republic",
	"Egypt",
	"Equatorial Guinea",
	"Germany",
	"India",
	"Israel",
	"Japan",
	"Latvia",
	"Lebanon",
	"Malaysia",
	"Mauritania",
	"Mexico",
	"Mongolia",
	"Morocco",
	"Nigeria",
	"Pakistan",
	"Panama",
	"Philippines",
	"Russian Federation",
	"Senegal",
	"Somalia",
	"South Africa",
	"Switzerland",
	"Togo",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"United States",
	"Zambia"
]

export const unesco = ["Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"benin",
	"bhutan",
	"Bolivia",
	"bosnia and herzegovia",
	"botswana",
	"Brazil",
	"brunei darussalam",
	"Bulgaria",
	"Burkina faso",
	"Burundi",
	"Cabo Verde",
	"cambodia",
	"Cameroon",
	"canada",
	"Central African Republic",
	"chad",
	"chile",
	"China",
	"colombia",
	"comoros",
	"Congo (Democratic Republic of the)",
	"cook islands",
	"costa rica",
	"Côte d'Ivoire",
	"croatia",
	"Cuba",
	"cyprus",
	"czechia",
	"denmark",
	"djibouti",
	"dominica",
	"dominican republic",
	"ecuador",
	"Egypt",
	"el salvador",
	"Equatorial Guinea",
	"eritrea",
	"estonia",
	"eswatini",
	"Ethiopia",
	"fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia (Republic of The)",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People’s Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia (Federated States of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"niue",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"palestine",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Republic of Moldova",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Türkiye",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom of Great Britain and Northern Ireland",
	"United Republic of Tanzania",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela, Bolivarian Republic of",
	"Viet Nam",
	"Yemen",
	"Zambia",
	"Zimbabwe"
]

export const unhrc = ["Algeria",
	"Argentina",
	"Bangladesh",
	"Belgium",
	"Benin",
	"Iran",
	"Iraq",
	"Yemen",
	"Libya",
	"Syria",
	"Venezuela",
	"Nicaragua",
	"Myanmar",
	"Bolivia (Plurinational state of)",
	"Cameroon",
	"Chile",
	"China",
	"Costa Rica",
	"Côte d’Ivoire",
	"Cuba",
	"Czechia",
	"Eritrea",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Honduras",
	"India",
	"Kazakhstan",
	"Kyrgyztan",
	"Lithuania",
	"Luxembourg",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mexico",
	"Montenegro",
	"Morocco",
	"Nepal",
	"Pakistan",
	"Paraguay",
	"Qatar",
	"Romania",
	"Senegal",
	"Somalia",
	"South Africa",
	"Sudan",
	"Ukraine",
	"United Arab Emirates",
	"United kingdom of Great Britain and Northern Ireland",
	"United States of America",
	"Uzbekistan",
	"Viet Nam"
]

export const unoosa = ["Albania",
	"Algeria",
	"Angola",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahrain",
	"Bangladesh",
	"Belarus",
	"Belgium",
	"Benin",
	"Bolivia",
	"Brazil",
	"Bulgaria",
	"Burkina Faso",
	"Cameroon",
	"Canada",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Costa Rica",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Ethiopia",
	"Finland",
	"France",
	"Germany",
	"Ghana",
	"Greece",
	"Guatemala",
	"Hungary",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Israel",
	"Italy",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kuwait",
	"Lebanon",
	"Libya",
	"Luxembourg",
	"Malaysia",
	"Mauritius",
	"Mexico",
	"Mongolia",
	"Morocco",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Norway",
	"Oman",
	"Pakistan",
	"Panama",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saudi Arabia",
	"Senegal",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"South Africa",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Thailand",
	"Tunisia",
	"Turkey (now Türkiye)",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom of Great Britain and Northern Ireland",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Venezuela",
	"Viet Nam"
]

export const unsc = ["Albania",
	"Brazil",
	"China",
	"Ecuador",
	"France",
	"Gabon",
	"Ghana",
	"Japan",
	"Malta",
	"Mozambique ",
	"Russian Federation",
	"Switzerland",
	"United Arab Emirates",
	"United Kingdom",
	"United States of America"
]

export const wha = ["International Federation of Medical Students Associations (IFMSA)",
	"World Medical Association (WMA)",
	"Global Alliance for Vaccines and Immunisation(GAVI)",
	"United Nations High Commission for Refugees(UNHCR)",
	"International Committee of the Red Cross(ICRC)",
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutna",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Cook Islands",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czechia",
	"Democratic People's Republic of Korea",
	"Democratic Republic of the Congo",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany ",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua ",
	"Niger",
	"Nigeria",
	"Niue",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Republic of Moldova",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Thailand",
	"Timore-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkiye",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom of Great Britain and Northern Ireland",
	"United Republic of Tanzania",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Viet Nam",
	"Yemen",
	"Zambia",
	"Zimbabwe"
]

export const worldbank = ["Afghanistan",
	"Albania",
	"Algeria",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas, The",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo, Dem. Rep.",
	"Congo, Rep.",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cyprus",
	"Czechia",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt, Arab Rep.",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia, The",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran, Islamic Rep.",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea, Rep.",
	"Kosovo",
	"Kuwait",
	"Kyrgyz Republic",
	"Lao PDR",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia, Fed. Sts.",
	"Moldova",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Portugal",
	"Qatar",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovak Republic",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"St. Kitts and Nevis",
	"St. Lucia",
	"St. Vincent and the Grenadines",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkiye",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela, RB",
	"Vietnam",
	"Yemen, Rep.",
	"Zambia",
	"Zimbabwe"
]

export const ip = ["Photographer", "Journalist"]

export const adhoc = ["Israel - Minister of Defense", "Israel - Chief of Mossad", "Israel - Foreign Affairs Minister", "Israel - Minister of Public Security", "Israel - Minister of Internal Affairs", "Palestine - Chairman of the Palestine Liberation Organizations Executive Committee", "Palestine - Chief of Intelligence", "Palestine - Minister of Foreign Affairs", "Palestine - Minister of Interior and National Security", "Palestine - Head of Hamas Political Bureau", "USA - Secretary of State", "USA - Secretary of Defense", "USA - Director of the CIA", "USA - Commander of U.S. CENTCOM", "USA - Commander of U.S. Fifth Fleet", "China - Foreign Minister", "China - Minister of National Defense", "China - Director of the Ministry of State Security", "China - Commander of the PLA Western Theater Command", "China - Chief of Staff of the PLA Navy", "Russia - Foreign Minister", "Russia - Minister of Defense", "Russia - Director of the SVR", "Russia - Commander of the Russian Southern Military District", "Russia - Commander of the Russian Navy Black Sea Fleet", "France - Foreign Minister", "France - Minister of the Armed Forces", "France - Director of DGSE", "France - Chief of Staff of the French Armed Forces", "Saudi Arabia - Foreign Minister", "Saudi Arabia - Chief of General Intelligence Presidency", "Saudi Arabia - Commander of the Royal Saudi Land Forces", "Jordan - Foreign Minister", "Jordan - Director of General Intelligence Directorate", "Jordan - Commander of the Jordanian Armed Forces"]

export function whatToMapCommitteeOne(values: FormikValues): string[] {
	var countryMapper: string[];
	switch (values.committeeOne) {
		case "DISEC":
			countryMapper = disec;
			break;
		case "UNHRC":
			countryMapper = unhrc;
			break;
		case "UNCSW":
			countryMapper = uncsw
			break;
		case "WHA":
			countryMapper = wha
			break;
		case "COP-28 UNFCCC":
			countryMapper = unfccc
			break;
		case "World bank":
			countryMapper = worldbank
			break;
		case "SC":
			countryMapper = unsc
			break;
		case "NATO":
			countryMapper = nato
			break;
		case "ECOSOC":
			countryMapper = ecosoc
			break;
		case "UNCND":
			countryMapper = uncnd
			break;
		case "GA6 Legal":
			countryMapper = uncsw
			break;
		case "UNOOSA":
			countryMapper = unoosa
			break;
		case "UNESCO":
			countryMapper = unesco
			break;
		case "IP":
			countryMapper = ip
			break;
		case "Ad Hoc":
			countryMapper = adhoc
			break
		default:
			countryMapper = [];
	}
	return countryMapper;
}

export function whatToMapCommitteeTwo(values: FormikValues): string[] {
	var countryMapper: string[];
	switch (values.committeeTwo) {
		case "DISEC":
			countryMapper = disec;
			break;
		case "UNHRC":
			countryMapper = unhrc;
			break;
		case "UNCSW":
			countryMapper = uncsw
			break;
		case "WHA":
			countryMapper = wha
			break;
		case "COP-28 UNFCCC":
			countryMapper = unfccc
			break;
		case "World bank":
			countryMapper = worldbank
			break;
		case "SC":
			countryMapper = unsc
			break;
		case "NATO":
			countryMapper = nato
			break;
		case "ECOSOC":
			countryMapper = ecosoc
			break;
		case "UNCND":
			countryMapper = uncnd
			break;
		case "GA6 Legal":
			countryMapper = uncsw
			break;
		case "UNOOSA":
			countryMapper = unoosa
			break;
		case "UNESCO":
			countryMapper = unesco
			break;
		case "IP":
			countryMapper = ip
			break;
		case "Ad Hoc":
			countryMapper = adhoc
			break

		default:
			countryMapper = [];
	}
	return countryMapper;
}

export function whatToMapCommitteeThree(values: FormikValues): string[] {
	var countryMapper: string[];
	switch (values.committeeThree) {
		case "DISEC":
			countryMapper = disec;
			break;
		case "UNHRC":
			countryMapper = unhrc;
			break;
		case "UNCSW":
			countryMapper = uncsw
			break;
		case "WHA":
			countryMapper = wha
			break;
		case "COP-28 UNFCCC":
			countryMapper = unfccc
			break;
		case "World bank":
			countryMapper = worldbank
			break;
		case "SC":
			countryMapper = unsc
			break;
		case "NATO":
			countryMapper = nato
			break;
		case "ECOSOC":
			countryMapper = ecosoc
			break;
		case "UNCND":
			countryMapper = uncnd
			break;
		case "GA6 Legal":
			countryMapper = uncsw
			break;
		case "UNOOSA":
			countryMapper = unoosa
			break;
		case "UNESCO":
			countryMapper = unesco
			break;
		case "IP":
			countryMapper = ip
			break;
		case "Ad Hoc":
			countryMapper = adhoc
			break
		default:
			countryMapper = [];
	}
	return countryMapper;
}
